#!/bin/bash
echo 'package de.srsoftware.intellimind;' > Version.java
echo '' >> Version.java
echo 'public class Version {' >> Version.java
echo '  public static String get(){' >> Version.java
echo -n '    return "' >> Version.java
echo -n "$(git symbolic-ref --short HEAD) / $(git rev-parse HEAD)\\n" >> Version.java
echo '";' >> Version.java
echo '  }' >> Version.java
echo '}' >> Version.java
